- hosts: web
  become: yes
  tasks:

    - name: Wait for dpkg lock
      shell: |
        while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
          sleep 3
        done

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-venv
          - git
          - nginx
        state: present
        update_cache: yes


    - name: Ensure application directory exists
      file:
        path: /opt/flaskapp
        state: directory
        mode: '0777'


    - name: Configure Nginx reverse proxy for Flask
      copy:
        dest: /etc/nginx/sites-available/flaskapp
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/flaskapp
        dest: /etc/nginx/sites-enabled/flaskapp
        state: link

    - name: Disable default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent   

    - name: Remove Ubuntu default Nginx config directory
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
 

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted


