name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
      - developer

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest


  deploy:
    name: Deploy to EC2
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Create private key file for SSH
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/labuser.pem
         chmod 600 ~/.ssh/labuser.pem

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible playbook
        working-directory: ansible
        run: ansible-playbook -i inventory.ini playbook.yml

      - name: Deploy Flask App via SSH
        run: |
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/labuser.pem ec2-user@${{ secrets.EC2_IP }} "
           cd /opt/flaskapp;
           rm -rf app;
           git clone https://github.com/${{ github.repository }} app;
           cd app;
           pip3 install -r requirements.txt;
           pkill -f app.py || true;
           nohup python3 app.py > app.log 2>&1 &
         "

